Repository Tadpole-finance/tadpole-finance.github.io, pull requests merged in 2020-12, with the labels that each got.

#4 Remove horizontal scrollbar
  faq.html
  genesis.html
  index.html
Labels: score-low

#39 staking page remove horizontal bar
  staking.html
Labels: score:very-low

#5 Add 2020 Copyright in footer
  footer.html
Labels: score:very-low(1)

#6 Fix typo in documentation in faq, The to Then
  faq.html
Labels: score:very-low(1)

#13 Fix typo techincal to technical
  faq.html
Labels: score:very-low(1)

#14 Update Get TAD Method Status
  faq.html
Labels: score:very-low(1)

#15 Please Update Circulation
  circulation
Labels: score:very-low(1)

#29 Beware or Be aware to suit the situation?
  genesis.html
Labels: score:very-low(1)

#31 Please Fix Available Amount to Stake When First Time Loading Page on staking.html
  staking.html
Labels: score:very-low(1)

#44 Update faq.html
  faq.html
Labels: score:very-low(1)

#65 change faq to documentation url
  header.html
Labels: score:low(2)
